sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t manojkannank/docker-read -f Dockerfile.dev .

script:
  - docker run -e CI=true manojkannank/docker-read npm run test
  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-read'
  env: 'DockerRead-env'
  bucket_name: 'elasticbeanstalk-us-east-2-879422780293'
  bucket_path: 'docker-read'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY