sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t manojkannank/docker-read -f Dockerfile.dev .

script:
  - docker run -e CI=true manojkannank/docker-read npm run test
